### ISSUE TITLE
`gpg.sh` broken on Ubuntu due to slightly-different output 

### ISSUE THREAD

**Issue by ivoanjo** [DataDog/yubikey#109]
Hey!

I'm running `gpg.sh` and my setup is breaking on this step:

```
You need a user ID to identify your key; the software constructs the user ID
from the Real Name, Comment and Email Address in this form:
    "Heinrich Heine (Der Dichter) <heinrichh@duesseldorf.de>"

Real name: Ivo Anjo
E-mail address: (HANGS HERE)
```

I did not know a lot about what the script was doing, but poking at it I found this step...

https://github.com/DataDog/yubikey/blob/925b9f7ace0bccb3434fa8eafa813ae3b31fa688/expect.sh#L182

...and the problem is that my `ykman` outputs "E-mail" and not "Email".

I fixed that one and it broke again for a similar reason in

```
You selected this USER-ID:
    "Ivo Anjo (GPG on YubiKey for Datadog) <ivo.anjo@datadoghq.com>"

Change (N)ame, (C)omment, (E)-mail or (O)kay/(Q)uit? 
```
Which is in
https://github.com/DataDog/yubikey/blob/925b9f7ace0bccb3434fa8eafa813ae3b31fa688/expect.sh#L188

Here's some of the versions I'm using:

```
ivo.anjo@rubyshade:~/datadog/yubikey$ ykman -v
YubiKey Manager (ykman) version: 5.0.0
ivo.anjo@rubyshade:~/datadog/yubikey$ env | grep LANG
LANGUAGE=en_GB:en
LANG=en_GB.UTF-8
ivo.anjo@rubyshade:~/datadog/yubikey$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

**Comment by trishankatdatadog** [comment]
Hey Ivo! Thanks for your report. Would it be possible to send a quick PR to fix this (without breaking other platforms ofc)?

**Comment by daisukixci** [comment]
We might need to split the expect by os. IMO it would be safer as ykman and gpg version are probably not sync between OSes

**Comment by ivoanjo** [comment]
> Would it be possible to send a quick PR to fix this (without breaking other platforms ofc)?

Sorry for the late reply! I may not be able to open a PR for this for some time, but if nobody fixes it in the meanwhile I may take a stab at it.

**Comment by daisukixci** [comment]
Drafted #110 if you could test

**Comment by ivoanjo** [comment]
@daisukixci thanks for looking into this! :bow: 

Is there a way to test it without nuking my current setup?
