### ISSUE TITLE
Handle homebrew installation / upgrade issues

### ISSUE THREAD

**Issue by trishankatdatadog** [DataDog/yubikey#13]
For some people, especially those with GPG already installed on their computer, `brew` has a difficult time upgrading our required packages without complaining about a whole bunch of things that must be resolved manually.

For example, here is what one user reported:

> I ran the brew command outside the script, since I was pretty sure that I had a bunch of old stuff installed
> * i needed to run brew update before running this to get the latest version of git (git commands failed with 2.17.1, didn't like --default option)
> * I needed to run xcode-select --install (python@2 failed before I ran this, succeeded after)
> * I already had gpg 2.2.8 installed (gpg (GnuPG/MacGPG2) 2.2.8).  This means I either need to run with gpg 2.2.8 instead of 2.2.10, or I need to force overwriting the gpg symlink (brew link --overwrite gnupg). I chose to leave the MacGPG 2.2.8 link but ran into an error exporting ssh key for the first run.
> 

Try to make this as easy as possible to handle for existing users (e.g., suggest what to do).

Cc: @dcoleman17

**Comment by daisukixci** [comment]
Since now the package installation is optional, can we close this @trishankatdatadog ?
