### ISSUE TITLE
mac.sh exited after selecting 'no' on ssh permission

### ISSUE THREAD

**Issue by ChristineTChen** [DataDog/yubikey#18]
The first time I ran the script to set up my backup Yubikey, the script exited after I answered No to the prompt "do you want to ssh to your yubikey". However, running the script a second time was successful and I didn't encounter this issue.

**Comment by trishankatdatadog** [comment]
@FlorianVeaux saw this today, too

The method that seems to have worked was to reload the gpg-agent [like so](https://superuser.com/questions/1075404/how-can-i-restart-gpg-agent/1150399)

**Comment by trishankatdatadog** [comment]
We no longer support SSH by default

d79be81906c0146c891328785f6c97dc76589842
