### ISSUE TITLE
Try `cached` touch policy before defaulting to `on`

### ISSUE THREAD

**Issue by trishankatdatadog** [DataDog/yubikey#43]
Unfortunately, #42 won't work for everyone, especially those with the FIPS key model. Therefore, we should default to the `on` touch policy after trying `cached` and it fails.

Cc @HadrienPatte

**Comment by daisukixci** [comment]
Does that mean we should revert the PR and maybe ask the user about it during script execution ?

**Comment by trishankatdatadog** [comment]
Something like that, yeah

**Comment by trishankatdatadog** [comment]
I don't think we should bother the user though, following our philosophy of defaulting to sensible values

**Comment by HadrienPatte** [comment]
I thought about it a bit, and I think we could go for the following workflow:
* First set the touch policy to `on` (works on every key)
* Then set it to `cached`, which will succeed and change the policy on newer keys and fail on others, in which case we let the script ignore the failure and continue and the policy will remain `on`

I should have a PR up before the end of the week, in the meantime you can revert the previous PR if you want

**Comment by trishankatdatadog** [comment]
Take your time
