### ISSUE TITLE
Q: How to setup on multiple machines?

### ISSUE THREAD

**Issue by donferi** [DataDog/yubikey#51]
This is a question and not an issue 😃 

I was wondering how can I set this up for multiple machines? I have two personal machines and looking at the code it will setup new gpg keys, reset yubikey, etc.

What if I want to setup this once on one machine but then setup everything on a second machine without recreating keys / reseting yubikey?

I understand if this is not a supported behavior.

**Comment by trishankatdatadog** [comment]
At this point, we do not support creating keys off-Yubikey, and then importing the same key into two different YubiKeys. The current behaviour is that running the same script on two different YubiKeys will give you two different sets of keys with no off-card backup.

You might wish to see [Dr. Duh's guide](https://github.com/drduh/YubiKey-Guide#multiple-yubikeys) for multiple YubiKeys.

**Comment by donferi** [comment]
Sorry I think I didn't phrase my question correctly. My question is about having multiple computers being able to use the same YubiKey (not at the same time). 

So basically after the initial setup in one computer then setup in a different computer to use the same YubiKey (setup ssh agent, sign commits, etc).

**Comment by trishankatdatadog** [comment]
You can just import the GPG pubkey on the second machine and use it from there. You can't use the same key on two different machines at the same time unless you do some sort of strange proxying (which I do not recommend at all).

**Comment by donferi** [comment]
Thanks for your replies!

**Comment by daisukixci** [comment]
@trishankatdatadog I think the question is how to get the second computer configured without using our scripts since when we run our script it reset the yubikey. 

If it's what you ask @donferi, on the second computer you have to:

- install pinentry-mac 
- put the following  in your `~/.gnupg/gpg-agent.conf`
```
pinentry-program /usr/local/bin/pinentry-mac
enable-ssh-support
```
- add the following in your RC configuration (works with bash and zsh, if you use another shel like fishl, you will need to adapt it)
```bash 
# Add gpg autostart
gpgconf --launch gpg-agent
export "SSH_AUTH_SOCK=${HOME}/.gnupg/S.gpg-agent.ssh"
```
- put in your `~/.gitconfig` (You can copy paste from the one the script set up for you)
```
[user]
	email = YOUR EMAIL
	name = YOUR NAME
	signingkey = YOUR KEY ID
[commit]
	gpgsign = true
[tag]
	forceSignAnnotated = true
```

**Comment by donferi** [comment]
@daisukixci This is exactly what I was looking for, thank you so much!

**Comment by daisukixci** [comment]
@trishankatdatadog will add a script to do it or in documentation

**Comment by trishankatdatadog** [comment]
> @trishankatdatadog will add a script to do it or in documentation

Is that an order or a notice? 😅

**Comment by daisukixci** [comment]
sorry x) it's a notice, I will do it
