### ISSUE TITLE
Repo local git config not working

### ISSUE THREAD

**Issue by paulcacheux** [DataDog/yubikey#96]
Hello, since the "lib-ification" of the git setup script, the local mode is not working because it "cd"s into the repo directory before sourcing the lib script with the actual setup.

Since the sourcing is done with a relative path, the target file cannot be found.

One solution would be to use the `OLD_PWD` variable that is saved before the switch case.

**Comment by daisukixci** [comment]
Hi, thanks for reporting, will take a look

**Comment by daisukixci** [comment]
Updated #95 to fix your issue, can you test it please.
